### ISSUE TITLE
[bisected] segmentation fault at start time with linphone-daemon after a3f4462dfb3f9cbe7b22be3dca826beb7111430e

### ISSUE THREAD

**Issue by balducci** [BelledonneCommunications/liblinphone#214]
hello

building linphone and dependencies on linux from git since quite a bit (years) and everything has always worked nicely.

(my specs are enclosed at the end of this report)

I'm now getting a segmentation fault with linphone-daemon at start time:

```
#> linphone-daemon
2022-07-22 16:47:32:360 belle-sip-warning-There is no object pool created in thread [139838175250560]. Use belle_sip_object_pool_push() to create one. Unowned objects not unref'd will be leaked.
Segmentation fault

```

gdb backtrace shows:

```
#> gdb linphone-daemon
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/linphone-deps/bin/linphone-daemon...
(gdb) run
Starting program: /usr/local/linphone-deps/bin/linphone-daemon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
2022-07-22 16:49:58:028 belle-sip-warning-There is no object pool created in thread [140737281337472]. Use belle_sip_object_pool_push() to create one. Unowned objects not unref'd will be leaked.

Program received signal SIGSEGV, Segmentation fault.
0x0000000000a0b3d8 in LinphonePrivate::Address::Address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
(gdb) bt
#0  0x0000000000a0b3d8 in LinphonePrivate::Address::Address(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#1  0x0000000000693172 in __static_initialization_and_destruction_0(int, int) [clone .constprop.0] ()
#2  0x00007ffff5e2b2a6 in call_init (env=<optimized out>, argv=0x7fffffffcbf8, 
    argc=1) at ../csu/libc-start.c:145
#3  __libc_start_main_impl (main=0x692240 <main>, argc=1, argv=0x7fffffffcbf8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffcbe8) at ../csu/libc-start.c:379
#4  0x000000000069bf11 in _start () at ../sysdeps/x86_64/start.S:115
(gdb) quit
```

The segmentation fault happens before linphone-daemon can write anything to its log file, so running:

```
#> linphonec --log /tmp/lp.log
```
doesn't help.

This started with revision number 15838 (822c3835bbf2b3b881a2aa0fa661f95f242e6a7e); my previous installation was for revision number 15833 (59d99bd981afe9d1748bf7d827deb64cca39beb3) and that works nicely as usual.

There were no new commits to all other dependencies in between (apart from a single commit to bctoolbox).

The following are all the dependencies I build with their respective master commits for my working (GOOD) and non working (BAD) builds:

GOOD:

```
    antlr          215    2017-08-24@12-16-10  127930409b59f5b0341de1141f5a0482a3a6aa68
    bcg729         151    2020-11-22@21-43-40  faaa895862165acde6df8add722ba4f85a25007d
    bctoolbox      776    2022-07-04@16-51-26  4661e5e81c3a818d1070bb4859df52c3add9b276
    bcunit         221    2022-02-10@10-32-10  e3557aed8ba22e04047a9e4371a331b863081fc8
    belcard        230    2022-01-27@13-56-56  f50f203d6a44b6ec3bfd897d8057a94dfefa3e57
    belle_sip      2104   2022-06-30@09-57-20  c5b1d558450852474f6e5196e87fe8ee6dd32582
    belr           196    2022-02-10@10-41-23  5b9f1ecb134f431b92a5d4bb5d4ca65ab4f47d59
    bzrtp          304    2022-06-10@14-35-52  11fa848778f36ed09cb927239e5901fa154c66ff
    libxsd         9      2018-10-30@14-09-11  5759c15081384973e30f20129bef13e71343ab0c
    lime           238    2022-05-27@14-59-00  5ec9ae690b3e1c0ba1b9cc46a6389ee185ef71f8
    linphone       15833  2022-07-06@11-18-38  59d99bd981afe9d1748bf7d827deb64cca39beb3
    mbedtls        15840  2022-06-13@12-06-23  a4f4f947c1c1dbaba7052a96eb4995a75aa4e523
    mediastreamer  6285   2022-06-17@22-39-57  9a8d00864c5e3f49d72192ecc427515ea88cf7a6
    ortp           1937   2022-07-08@12-33-45  bd49d3edbe4b8cf450827d3ddd939ca70e339135
    soci           2449   2022-03-16@09-34-53  bc8ce0c5628dd48eca6ef5ce0a0a2f52547d88b6
    srtp           1357   2022-07-02@23-16-22  2481874bc4c24cdcc16577313d9460f8423dc57c
    xerces_c       20     2021-03-16@11-56-45  5e778ef931f63f709eb175b232813dd26afb3ae1
```

BAD:

```
    antlr          215    2017-08-24@12-16-10  127930409b59f5b0341de1141f5a0482a3a6aa68
    bcg729         151    2020-11-22@21-43-40  faaa895862165acde6df8add722ba4f85a25007d
    bctoolbox      777    2022-02-25@12-32-22  794c26a102ee5497df4aa7a2d1672090eba67a10
    bcunit         221    2022-02-10@10-32-10  e3557aed8ba22e04047a9e4371a331b863081fc8
    belcard        230    2022-01-27@13-56-56  f50f203d6a44b6ec3bfd897d8057a94dfefa3e57
    belle_sip      2104   2022-06-30@09-57-20  c5b1d558450852474f6e5196e87fe8ee6dd32582
    belr           196    2022-02-10@10-41-23  5b9f1ecb134f431b92a5d4bb5d4ca65ab4f47d59
    bzrtp          304    2022-06-10@14-35-52  11fa848778f36ed09cb927239e5901fa154c66ff
    libxsd         9      2018-10-30@14-09-11  5759c15081384973e30f20129bef13e71343ab0c
    lime           238    2022-05-27@14-59-00  5ec9ae690b3e1c0ba1b9cc46a6389ee185ef71f8
    linphone       15838  2022-07-12@15-51-07  822c3835bbf2b3b881a2aa0fa661f95f242e6a7e
    mbedtls        15840  2022-06-13@12-06-23  a4f4f947c1c1dbaba7052a96eb4995a75aa4e523
    mediastreamer  6285   2022-06-17@22-39-57  9a8d00864c5e3f49d72192ecc427515ea88cf7a6
    ortp           1937   2022-07-08@12-33-45  bd49d3edbe4b8cf450827d3ddd939ca70e339135
    soci           2449   2022-03-16@09-34-53  bc8ce0c5628dd48eca6ef5ce0a0a2f52547d88b6
    srtp           1357   2022-07-02@23-16-22  2481874bc4c24cdcc16577313d9460f8423dc57c
    xerces_c       20     2021-03-16@11-56-45  5e778ef931f63f709eb175b232813dd26afb3ae1
```

Manual bisection of liblinphone between 15833 (59d99bd981afe9d1748bf7d827deb64cca39beb3) (GOOD) and 15838 (822c3835bbf2b3b881a2aa0fa661f95f242e6a7e) (BAD) points to this as the first bad commit (revno 15837):

```
commit a3f4462dfb3f9cbe7b22be3dca826beb7111430e
Author: Thibault Lemaire <thibault.lemaire@belledonne-communications.com>
Date:   Thu Jun 2 16:45:05 2022 +0200

    feat: Add Call::getRequestAddress()
    
    Useful when calls are being forwarded (e.g. from a proxy to a B2BUA).
    The To field would then be different from the address the SIP invite is
    sent to.
```

Thanks for any help
ciao
-gabriele

Configuring with:

```
-DENABLE_GTK_UI=ON
-DCMAKE_SKIP_INSTALL_RPATH=YES
-DCMAKE_SKIP_RPATH=YES
```

Compiler/linker/glibc:

```
#> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/stow.d/versions/gcc-12.1.0/usr/lib64/gcc/x86_64-pc-linux-gnu/12.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /home/balducci/tmp/install-us-d/gcc-12.1.0.d/gcc-12.1.0/configure --prefix=/opt/stow.d/versions/gcc-12.1.0/usr --libdir=/opt/stow.d/versions/gcc-12.1.0/usr/lib64 --libexecdir=/opt/stow.d/versions/gcc-12.1.0/usr/lib64 --enable-shared --disable-bootstrap --enable-languages=c,c++,objc,fortran --enable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.0 (GCC) 
```

```
#> ld --version
GNU ld (GNU Binutils) 2.38
Copyright (C) 2022 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

```
#> /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.35.
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 12.1.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://www.gnu.org/software/libc/bugs.html>.
```

kernel:

```
#> uname -srvmo
Linux 5.18.12 #1 SMP Sat Jul 16 08:27:34 CEST 2022 x86_64 GNU/Linux
```

**Comment by balducci** [comment]
This issue has been fixed by 44fb94caa2ebb40ef3daab720019d46f3f0605af:

```
    commit 44fb94caa2ebb40ef3daab720019d46f3f0605af
    Author: Simon Morlat <simon.morlat@linphone.org>
    Date:   Fri Dec 23 08:24:27 2022 +0100

        Fix crash at startup due to non-deterministic order of c++
    static initializers.
```
