### ISSUE TITLE
couldn't find "libgnustl_shared.so"

### ISSUE THREAD

**Issue by liulanghaitun** [BelledonneCommunications/liblinphone#53]
when I compile Linphone with Android Studio,I got the error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.linphone, PID: 5358
                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.linphone-2/base.apk", zip file "/data/app/org.linphone-2/split_lib_dependencies_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_0_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_1_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_2_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_3_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_4_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_5_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_6_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_7_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_8_apk.apk", zip file "/data/app/org.linphone-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libgnustl_shared.so"
                      at java.lang.Runtime.loadLibrary(Runtime.java:366)
                      at java.lang.System.loadLibrary(System.java:988)
                      at org.linphone.core.LinphoneCoreFactoryImpl.<clinit>(LinphoneCoreFactoryImpl.java:46)
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:309)
                      at java.lang.Class.forName(Class.java:273)
                      at org.linphone.core.LinphoneCoreFactory.instance(LinphoneCoreFactory.java:47)
                      at org.linphone.LinphoneService.onCreate(LinphoneService.java:300)
                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2809)
                      at android.app.ActivityThread.access$1800(ActivityThread.java:154)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:134)
                      at android.app.ActivityThread.main(ActivityThread.java:5377)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

How should I solve this problem ?

**Comment by liulanghaitun** [comment]
I found the answer.
change to top level dir,apply  ./prepare.py .
and then exec make
This library can be generated.

**Comment by iampato** [comment]
anybody else solved this?
